"""
Adaptive Letter Generator - dynamically builds letters based on detected issues.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Literal

from src.letters.sections import SectionLibrary


ToneType = Literal['polite', 'professional', 'firm']


class AdaptiveLetterGenerator:
    """Generates letters that adapt to detected issues."""
    
    def __init__(self, analysis_result: Dict):
        """
        Initialize with agent analysis result.
        
        Args:
            analysis_result: Output from BillShieldAgent.analyze()
        """
        self.analysis = analysis_result
        self.available_sections = SectionLibrary.get_all_sections()
    
    def generate_hospital_letter(
        self,
        tone: ToneType = 'professional',
        patient_name: str = "[Patient Name]",
        hospital_name: str = "[Hospital Name]",
        bill_number: str = "[Bill Number]"
    ) -> str:
        """Generate hospital objection letter with only relevant sections."""
        
        # Header
        parts = []
        parts.append("HOSPITAL BILLING OBJECTION LETTER")
        parts.append("=" * 60)
        parts.append("")
        parts.append(f"Date: {datetime.now().strftime('%B %d, %Y')}")
        parts.append(f"Patient Name: {patient_name}")
        parts.append(f"Bill Number: {bill_number}")
        parts.append(f"Total Bill Amount: ₹{self.analysis.get('total_bill', 0):,.0f}")
        parts.append("")
        parts.append(f"To: Billing Department")
        parts.append(f"{hospital_name}")
        parts.append("")
        parts.append("Subject: Objection to Billing Charges - Overcharges Detected")
        parts.append("")
        
        # Greeting based on tone
        if tone == 'polite':
            greeting = "Dear Sir/Madam,\n\nI hope this letter finds you well. I am writing regarding some concerns with my recent hospital bill."
        elif tone == 'firm':
            greeting = "Dear Sir/Madam,\n\nI am writing to formally object to significant overcharges in the referenced hospital bill."
        else:
            greeting = "Dear Sir/Madam,\n\nI am writing to object to certain charges in the above-referenced hospital bill."
        
        parts.append(greeting)
        parts.append("")
        
        # Add applicable sections
        applicable_sections = self._get_applicable_sections()
        
        if not applicable_sections:
            parts.append("No overcharges detected.")
        else:
            parts.append("VERIFIED OVERCHARGES:")
            parts.append("")
            
            for section in sorted(applicable_sections, key=lambda s: s.priority, reverse=True):
                content = section.content_builder(self.analysis, tone)
                parts.append(f"## {section.title}")
                parts.append(content)
                parts.append("")
        
        # Regulatory references (only ones actually cited)
        refs = self._build_regulatory_references()
        if refs:
            parts.append("REGULATORY REFERENCES:")
            parts.append(refs)
            parts.append("")
        
        # Closing based on tone
        verified_total = self.analysis.get('total_verified_overcharge', 0)
        
        parts.append("REQUESTED ACTION:")
        if tone == 'polite':
            parts.append(f"I kindly request a review of the above charges. Please provide:")
        elif tone == 'firm':
            parts.append(f"I demand immediate correction of the above overcharges. Provide:")
        else:
            parts.append(f"I request an immediate review. Please provide:")
        
        parts.append("1. Revised bill with corrected amounts")
        parts.append("2. Written justification for any charges you believe are correct")
        parts.append(f"3. Refund of ₹{verified_total:,.0f} within 15 days")
        parts.append("")
        
        if tone == 'firm':
            parts.append("Failure to address these overcharges will result in escalation to the consumer forum.")
        else:
            parts.append("I am prepared to escalate this matter if the overcharges are not addressed.")
        
        parts.append("")
        parts.append("Yours sincerely,")
        parts.append(patient_name)
        parts.append("")
        parts.append("---")
        parts.append("Generated by BillShield Medical Bill Auditor")
        
        return "\n".join(parts)

    def generate_insurer_letter(
        self,
        tone: ToneType = 'firm',
        patient_name: str = "[Patient Name]",
        insurer_name: str = "[Insurance Company]",
        policy_number: str = "[Policy Number]",
        claim_number: str = "[Claim Number]"
    ) -> str:
        """Generate insurer escalation letter for invalid rejections."""
        
        parts = []
        parts.append("INSURANCE CLAIM ESCALATION LETTER")
        parts.append("=" * 60)
        parts.append("")
        parts.append(f"Date: {datetime.now().strftime('%B %d, %Y')}")
        parts.append(f"Policy Number: {policy_number}")
        parts.append(f"Claim Number: {claim_number}")
        parts.append(f"Policyholder: {patient_name}")
        parts.append("")
        parts.append(f"To: Grievance Redressal Officer")
        parts.append(f"{insurer_name}")
        parts.append("")
        parts.append("Subject: Escalation of Claim Rejection - IRDAI Regulation Violations")
        parts.append("")
        
        # Greeting based on tone
        if tone == 'polite':
            greeting = "Dear Sir/Madam,\n\nI am writing to request a review of my claim rejection."
        elif tone == 'firm':
            greeting = "Dear Sir/Madam,\n\nI am escalating the rejection of my health insurance claim due to violations of IRDAI regulations."
        else:
            greeting = "Dear Sir/Madam,\n\nI am writing to escalate the rejection of my claim based on IRDAI regulation concerns."
        
        parts.append(greeting)
        parts.append("")
        
        # Financial summary
        total_claim = self.analysis.get('total_bill', 0)
        approved = self.analysis.get('total_approved', 0)
        rejected = self.analysis.get('total_rejected', 0)
        
        parts.append("CLAIM DETAILS:")
        parts.append(f"Total Claim Amount: ₹{total_claim:,.0f}")
        parts.append(f"Amount Approved: ₹{approved:,.0f}")
        parts.append(f"Amount Rejected: ₹{rejected:,.0f}")
        parts.append("")
        
        # Only show rejection-related issues
        rejection_issues = [
            i for i in self.analysis.get('issues', [])
            if i.get('issue_type') in ['rejection_invalid', 'rejection_delayed', 'policy_violation']
        ]
        
        if rejection_issues:
            parts.append("IRDAI REGULATION VIOLATIONS:")
            parts.append("")
            
            for issue in rejection_issues:
                desc = issue.get('description', '')
                amount = issue.get('overcharge_amount', 0)
                evidence = issue.get('evidence', [])
                
                parts.append(f"• {desc}")
                if amount > 0:
                    parts.append(f"  Amount: ₹{amount:,.0f}")
                
                # Include key evidence points
                for ev in evidence[:2]:
                    parts.append(f"  - {ev}")
                
                parts.append("")
            
            total_recoverable = sum(i.get('overcharge_amount', 0) for i in rejection_issues)
            parts.append(f"Total potentially recoverable from invalid rejections: ₹{total_recoverable:,.0f}")
            parts.append("")
        
        # Regulatory references
        parts.append("IRDAI REGULATORY REFERENCES:")
        parts.append("- IRDAI Master Circular on Health Insurance Business (2024)")
        parts.append("- IRDAI (Protection of Policyholders' Interests) Regulations")
        parts.append("- Insurance Act, 1938 - Section 45 (Moratorium Period)")
        parts.append("")
        
        # Requested action
        parts.append("REQUESTED ACTION:")
        if tone == 'polite':
            parts.append("I kindly request:")
        elif tone == 'firm':
            parts.append("I demand the following within 7 days:")
        else:
            parts.append("I request:")
        
        parts.append("1. Immediate review of rejected items against IRDAI non-payable list")
        parts.append("2. Re-approval of unjustified rejections")
        parts.append("3. Written explanation for any timeline violations")
        parts.append("4. Settlement within IRDAI-mandated timelines")
        parts.append("")
        
        # Escalation warning
        if tone == 'firm':
            parts.append("If this matter is not resolved within 14 days, I will:")
        else:
            parts.append("If unresolved within 14 days, I will escalate to:")
        
        parts.append("- Insurance Ombudsman")
        parts.append("- IRDAI Integrated Grievance Management System (IGMS)")
        parts.append("- Bima Bharosa portal")
        parts.append("")
        
        parts.append("Yours sincerely,")
        parts.append(patient_name)
        parts.append("")
        parts.append("---")
        parts.append("Generated by BillShield Medical Bill Auditor")
        
        return "\n".join(parts)

    def generate_patient_summary(
        self,
        patient_name: str = "[Patient Name]"
    ) -> str:
        """Generate executive summary for patient."""
        
        parts = []
        parts.append("BILLSHIELD ANALYSIS REPORT - EXECUTIVE SUMMARY")
        parts.append("=" * 70)
        parts.append("")
        parts.append(f"Patient: {patient_name}")
        parts.append(f"Analysis Date: {datetime.now().strftime('%B %d, %Y')}")
        parts.append("")
        parts.append("=" * 70)
        parts.append("")
        
        # Financial overview
        total_bill = self.analysis.get('total_bill', 0)
        approved = self.analysis.get('total_approved', 0)
        rejected = self.analysis.get('total_rejected', 0)
        liability = self.analysis.get('total_patient_liability', 0)
        verified = self.analysis.get('total_verified_overcharge', 0)
        
        min_rec = self.analysis.get('estimated_recoverable', {}).get('min', 0)
        max_rec = self.analysis.get('estimated_recoverable', {}).get('max', 0)
        
        savings_pct = (min_rec / liability * 100) if liability > 0 else 0
        
        parts.append("FINANCIAL OVERVIEW:")
        parts.append("─" * 70)
        parts.append(f"Hospital Bill Total:        ₹{total_bill:>12,.0f}")
        parts.append(f"Insurance Approved:         ₹{approved:>12,.0f}")
        parts.append(f"Insurance Rejected:         ₹{rejected:>12,.0f}")
        parts.append(f"Your Out-of-Pocket:         ₹{liability:>12,.0f}")
        parts.append("")
        parts.append("RECOVERY POTENTIAL:")
        parts.append("─" * 70)
        parts.append(f"Verified Overcharges:       ₹{verified:>12,.0f}")
        parts.append(f"Estimated Recoverable:      ₹{min_rec:>12,.0f} - ₹{max_rec:,.0f}")
        parts.append(f"Potential Savings:          {savings_pct:>12.0f}% of your liability")
        parts.append("")
        parts.append("=" * 70)
        parts.append("")
        
        # Issues by confidence
        issues = self.analysis.get('issues', [])
        high_conf = [i for i in issues if i.get('confidence') == 'high']
        medium_conf = [i for i in issues if i.get('confidence') == 'medium']
        
        parts.append(f"ISSUES DETECTED: {len(issues)}")
        parts.append("")
        
        if high_conf:
            parts.append(f"HIGH CONFIDENCE ISSUES ({len(high_conf)}):")
            parts.append("These are verifiable against government benchmarks:")
            parts.append("")
            
            for issue in high_conf[:5]:
                desc = issue.get('description', '')
                amount = issue.get('overcharge_amount', 0)
                issue_type = issue.get('issue_type', '')
                
                parts.append(f"• {desc}")
                parts.append(f"  Amount: ₹{amount:,.0f} | Type: {issue_type}")
                parts.append("")
            
            if len(high_conf) > 5:
                parts.append(f"...and {len(high_conf) - 5} more high-confidence issues.")
                parts.append("")
        
        if medium_conf:
            parts.append(f"MEDIUM CONFIDENCE ISSUES ({len(medium_conf)}):")
            parts.append("These require insurer review:")
            parts.append("")
            
            for issue in medium_conf[:3]:
                desc = issue.get('description', '')
                amount = issue.get('overcharge_amount', 0)
                
                parts.append(f"• {desc}")
                parts.append(f"  Amount: ₹{amount:,.0f}")
                parts.append("")
        
        parts.append("=" * 70)
        parts.append("")
        
        # Action plan
        parts.append("RECOMMENDED ACTIONS:")
        parts.append("")
        parts.append("IMMEDIATE (Within 7 Days):")
        parts.append("1. Send hospital objection letter (generated) via registered post")
        parts.append("2. Send insurer escalation letter (generated) via email + registered post")
        parts.append("3. Request itemized bill breakdown if not provided")
        parts.append("")
        parts.append("IF NO RESPONSE (After 14 Days):")
        parts.append("4. File consumer complaint at District Consumer Forum")
        parts.append("5. File insurance grievance at Bima Bharosa portal")
        parts.append("6. Contact Insurance Ombudsman for your region")
        parts.append("")
        parts.append("DOCUMENTS TO KEEP READY:")
        parts.append("- Original hospital bills and receipts")
        parts.append("- Discharge summary")
        parts.append("- Insurance policy document")
        parts.append("- This BillShield analysis report")
        parts.append("- Proof of registered post delivery")
        parts.append("")
        parts.append("=" * 70)
        parts.append("")
        parts.append("NEXT STEPS CHECKLIST:")
        parts.append("☐ Review all detected issues carefully")
        parts.append("☐ Send hospital objection letter")
        parts.append("☐ Send insurer escalation letter")
        parts.append("☐ Set reminder for 14-day follow-up")
        parts.append("☐ Prepare consumer complaint if needed")
        parts.append("")
        parts.append("=" * 70)
        parts.append("")
        parts.append("Generated by BillShield Medical Bill Auditor")
        
        return "\n".join(parts)
    
    def _get_applicable_sections(self) -> List:
        """Get only sections that apply to this analysis."""
        return [
            section for section in self.available_sections
            if section.applies_when(self.analysis) and section.user_enabled
        ]
    
    def _build_regulatory_references(self) -> str:
        """Build list of only cited regulations."""
        cited_regs = set()
        
        for issue in self.analysis.get('issues', []):
            for evidence in issue.get('evidence', []):
                if 'CGHS' in evidence:
                    cited_regs.add("- CGHS Rate Schedule 2025 (Central Government Health Scheme)")
                if 'NPPA' in evidence and 'device' in evidence.lower():
                    cited_regs.add("- NPPA Medical Device Price Ceilings (April 2026 revision)")
                if 'NPPA' in evidence and 'drug' in evidence.lower():
                    cited_regs.add("- NPPA Drug Price Control Orders")
                if 'IRDAI' in evidence:
                    cited_regs.add("- IRDAI Master Circular 2024 / Multi-Procedure Billing Guidelines")
        
        return "\n".join(sorted(cited_regs))


def generate_all_letters(analysis_result_path: Path, output_dir: Path, tone: ToneType = 'professional'):
    """Generate all letter types from an analysis result JSON."""
    
    with open(analysis_result_path, 'r') as f:
        analysis = json.load(f)
    
    generator = AdaptiveLetterGenerator(analysis)
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Hospital letter
    hospital_letter = generator.generate_hospital_letter(tone=tone)
    (output_dir / 'hospital_objection_letter.txt').write_text(hospital_letter)
    
    print(f"✅ Generated hospital letter ({tone} tone)")
    print(f"   Saved to: {output_dir / 'hospital_objection_letter.txt'}")